### ISSUE TITLE
undefined method `supervise_as' for Quickdraw::ShopifyConnector:Class (NoMethodError)

### ISSUE THREAD

**Issue by dux** [joeldrapper/quickdraw#33]
When I run `bundle exec quickdraw test` after fresh gem install, `ShopifyConnector` is for some reason loaded. I do not use Shopify.

```
bundler: failed to load command: quickdraw (/Users/dux/.asdf/installs/ruby/3.2.2/bin/quickdraw)
/Users/dux/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/quickdraw-0.0.4/lib/quickdraw/shopify_connector.rb:104:in `<module:Quickdraw>': undefined method `supervise_as' for Quickdraw::ShopifyConnector:Class (NoMethodError)

	ShopifyConnector.supervise_as(:shopify_connector)
	                ^^^^^^^^^^^^^
```

Also `bundle exec qt`

```
bundler: command not found: qt
Install missing gem executables with `bundle install`
```

**Comment by joeldrapper** [comment]
Hey @dux, this gem isn’t really ready for use yet, but it’s definitely useful to have folks trying it out.

The correct command is `bundle exec qt`, but this won't work on the released version of the gem, which was only released to save the `quickdraw` name on RubyGems. If you want to try quickdraw today, you need configure Bundler to pull it from GitHub.

```ruby
gem "quickdraw", git: "https://github.com/joeldrapper/quickdraw.git"
```

Once this is installed, you should be able to run tests with

```
bundle exec qt
```

It will look for files ending with `.test.rb`.

**Comment by dux** [comment]
thx, will try.
