### ISSUE TITLE
`qt` finds and tries to run its own tests when vendored

### ISSUE THREAD

**Issue by stevegeek** [joeldrapper/quickdraw#38]
When installed in `vendor/`  `qt` will pickup and run its own tests as its doing `Dir.glob(ARGV[0] || "./**/*.test.rb")`

Even in future when `qt` is installed as a gem and I assume its tests wont be in the gem build, then fact its picking up tests by default from `vendor/` is prob unexpected ?

**Comment by joeldrapper** [comment]
We could probably exclude `vendor` in our glob. I don’t know if this will work, but worth a shot:
```
"./{,!(vendor)/**}/*.test.rb"
```

**Comment by joeldrapper** [comment]
I think this is now handled by moving all quickdraw tests out of `lib`.
